### ISSUE TITLE
Feature-Request:  possible to add same hardware and mqtt options as in nukihub?

### ISSUE THREAD

**Issue by Ilovegym66** [technyon/blescanner#2]
Hi,
its possible to add all the options and services like in Nukihub? 
I use the nukihub on 5 ESP's without pairing to a lock, because I have more options, like mqtt-log, etc..

**Comment by technyon** [comment]
I'm not sure what your question is. You could NUKI Hub, disable the lock and the opener and use for presence detection ... which would be the only additional functionality I think beyond lock control.

**Comment by Ilovegym66** [comment]
I mean more or less to merge both in one .. but you're right, the solution have I now is your proposal..

**Comment by technyon** [comment]
Keeping the code bases synced is difficult. I try to update it every now and then, but it gets more and more difficult the more functionality there is in NUKI Hub.
